baseURL: "https://blog.uget.cz"
languageCode: "en-us"
title: "Uget Blog"
pygmentsstyle: 'monokai'

# Theme settings
theme: novela
paginate: 4
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
